import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar";
import SideBar from "./sidebar";

export const metadata: Metadata = {
  title: "Prescreening UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-axiforma antialiased bg-[#FAFAFB]`}
      >
        <Navbar/>
        <div className="flex justify-center relative">
          <SideBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
